// ============================================================================
// InterChatMessage.swift
// inter
//
// Phase 8.1.1 — Chat message model for in-meeting communication.
//
// Codable struct sent over LiveKit DataChannel (topic "chat").
// Supports public messages, direct messages, system announcements,
// and control signals (raise hand, lower hand).
//
// ISOLATION INVARIANT [G8]:
// This file defines pure data types only. No side effects, no UI,
// no room references. Safe to use from any thread.
// ============================================================================

import Foundation

// MARK: - Message Type

/// The kind of chat message. Determines routing and UI presentation.
@objc public enum InterChatMessageType: Int, Codable {
    /// Visible to all participants in the room.
    case publicMessage = 0
    /// Visible only to the sender and a specific recipient (Pro tier).
    case directMessage = 1
    /// System-generated announcement (e.g. "Alice joined the room").
    case system = 2
}

// MARK: - Control Signal Type

/// Control signals sent on the "control" DataChannel topic.
@objc public enum InterControlSignalType: Int, Codable {
    /// Participant raised their hand to speak.
    case raiseHand = 0
    /// Participant (or host) lowered a raised hand.
    case lowerHand = 1

    // Phase 9.2 — Advanced moderation signals
    /// Host disabled chat for all participants.
    case disableChat = 10
    /// Host re-enabled chat.
    case enableChat = 11
    /// Host is asking a participant to unmute their microphone.
    case askToUnmute = 12
    /// Meeting has been locked by host.
    case meetingLocked = 13
    /// Meeting has been unlocked.
    case meetingUnlocked = 14
    /// A participant has been suspended (all tracks muted + chat disabled).
    case suspended = 15
    /// A participant has been unsuspended.
    case unsuspended = 16
    /// Host-forced spotlight — all clients should spotlight this participant.
    case forceSpotlight = 17
    /// Clear host-forced spotlight — return to local control.
    case clearForceSpotlight = 18
    /// Participant was removed (notification before disconnect).
    case participantRemoved = 19
    /// Role change notification broadcast.
    case roleChanged = 20
    /// Lobby join notification (sent to host).
    case lobbyJoin = 21
    /// Host requests all participants to unmute their microphones.
    case requestUnmuteAll = 22
    /// Host has muted all participants' microphones (server-side mute + notification).
    case requestMuteAll = 23
    /// Participant requests permission to speak (when host-muted).
    case requestToSpeak = 24
    /// Host allows a participant to unmute and speak.
    case allowToSpeak = 25

    // Phase 10 — Recording consent notification signals
    /// A host/co-host has started recording. All participants receive this to show the REC indicator.
    case recordingStarted = 26
    /// Recording has been paused by the host/co-host.
    case recordingPaused = 27
    /// Recording has been resumed after a pause.
    case recordingResumed = 28
    /// Recording has been stopped. Participants should hide the REC indicator.
    case recordingStopped = 29
}

// MARK: - Chat Message

/// A single chat message exchanged via LiveKit DataChannel.
///
/// JSON-encoded for transport. The `id` is a UUID generated by the sender,
/// used for deduplication if the same message arrives twice during reconnect.
public struct InterChatMessage: Codable, Identifiable, Equatable {

    /// Unique message ID (UUID string, generated by sender).
    public let id: String

    /// LiveKit participant identity of the sender.
    public let senderIdentity: String

    /// Human-readable display name of the sender.
    public let senderName: String

    /// Message body text.
    public let text: String

    /// Unix timestamp (seconds since epoch) when the message was created.
    public let timestamp: TimeInterval

    /// Message type (public, DM, system).
    public let type: InterChatMessageType

    /// For DMs: the recipient's participant identity. Empty for public/system.
    public let recipientIdentity: String

    // MARK: - Init

    public init(
        id: String = UUID().uuidString,
        senderIdentity: String,
        senderName: String,
        text: String,
        timestamp: TimeInterval = Date().timeIntervalSince1970,
        type: InterChatMessageType = .publicMessage,
        recipientIdentity: String = ""
    ) {
        self.id = id
        self.senderIdentity = senderIdentity
        self.senderName = senderName
        self.text = text
        self.timestamp = timestamp
        self.type = type
        self.recipientIdentity = recipientIdentity
    }

    // MARK: - Serialization

    /// Encode this message to JSON Data for DataChannel transport.
    public func toJSONData() -> Data? {
        try? JSONEncoder().encode(self)
    }

    /// Decode a message from JSON Data received via DataChannel.
    public static func fromJSONData(_ data: Data) -> InterChatMessage? {
        try? JSONDecoder().decode(InterChatMessage.self, from: data)
    }
}

// MARK: - Control Signal

/// A control signal exchanged via LiveKit DataChannel (topic "control").
///
/// Used for raise hand, lower hand, and Phase 9 moderation signals
/// (disable chat, ask to unmute, suspend, force spotlight, etc.).
public struct InterControlSignal: Codable {

    /// Signal type.
    public let type: InterControlSignalType

    /// LiveKit participant identity of the sender.
    public let senderIdentity: String

    /// Human-readable display name of the sender.
    public let senderName: String

    /// The participant this signal is directed at (for host-initiated actions like dismiss).
    /// nil for self-originated signals (raise/lower own hand).
    public let targetIdentity: String?

    /// Unix timestamp (seconds since epoch).
    public let timestamp: TimeInterval

    /// Additional data payload for Phase 9 signals.
    /// Used for: role name in roleChanged, target identities list in forceSpotlight, etc.
    public let extraData: [String: String]?

    // MARK: - Init

    public init(
        type: InterControlSignalType,
        senderIdentity: String,
        senderName: String,
        targetIdentity: String? = nil,
        timestamp: TimeInterval = Date().timeIntervalSince1970,
        extraData: [String: String]? = nil
    ) {
        self.type = type
        self.senderIdentity = senderIdentity
        self.senderName = senderName
        self.targetIdentity = targetIdentity
        self.timestamp = timestamp
        self.extraData = extraData
    }

    // MARK: - Serialization

    public func toJSONData() -> Data? {
        try? JSONEncoder().encode(self)
    }

    public static func fromJSONData(_ data: Data) -> InterControlSignal? {
        try? JSONDecoder().decode(InterControlSignal.self, from: data)
    }
}

// MARK: - ObjC-Friendly Wrapper

/// Objective-C accessible wrapper for chat message properties.
/// Used by the ObjC UI layer (InterChatPanel) to display messages.
@objc public class InterChatMessageInfo: NSObject {

    @objc public let messageId: String
    @objc public let senderIdentity: String
    @objc public let senderName: String
    @objc public let text: String
    @objc public let timestamp: TimeInterval
    @objc public let messageType: InterChatMessageType
    @objc public let recipientIdentity: String

    /// Whether this is a message sent by the local participant.
    @objc public var isFromLocalUser: Bool = false

    public init(from message: InterChatMessage, isLocal: Bool = false) {
        self.messageId = message.id
        self.senderIdentity = message.senderIdentity
        self.senderName = message.senderName
        self.text = message.text
        self.timestamp = message.timestamp
        self.messageType = message.type
        self.recipientIdentity = message.recipientIdentity
        self.isFromLocalUser = isLocal
        super.init()
    }

    /// Formatted timestamp string (HH:mm).
    @objc public var formattedTime: String {
        let date = Date(timeIntervalSince1970: timestamp)
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm"
        return formatter.string(from: date)
    }

    /// Convenience initializer for system messages (used by moderation UI).
    @objc public convenience init(systemText: String) {
        let msg = InterChatMessage(
            id: UUID().uuidString,
            senderIdentity: "system",
            senderName: "System",
            text: systemText,
            timestamp: Date().timeIntervalSince1970,
            type: .system,
            recipientIdentity: ""
        )
        self.init(from: msg, isLocal: false)
    }
}
